lives: 3

dungeonspawn: x;y;z;world-differentfrom-lobby

lobbyspawn: x;y;z;world

no-lives-death: '&c%player% died! He doesn''t have more lifes'

lost-one-life: '&c%player lost 1 life! (%lifes%/%max%)'

already-started: 'Game altready started'

not-started: 'You didn''t start the game'

commands:
  start:
    - 'broadcast '
    - 'no slash needed!'
  end:
    - 'give %player% dirt 64'

